-- limit 원하는 행 개수만큼 뽑기
SELECT FLAVOR
FROM (
    SELECT F.FLAVOR AS FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS TOTAL_SUM
    FROM FIRST_HALF AS F JOIN JULY AS J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY F.FLAVOR
    ORDER BY TOTAL_SUM DESC
    ) AS CAL
LIMIT 3